### ISSUE TITLE
image file names

### ISSUE THREAD

**Issue by davidcarlisle** [dopefishh/rutitlepage#12]
The logo.xxx image files have very generic names which can easily be included by accident in unrelated documents as they are installed in the globally available search path in texlive.

This can cause confusion eg

https://tex.stackexchange.com/questions/459320/search-order-of-graphic-files

Would you consider prefixing all the images as (say) `ru-logo.pdf` and adjusting the inclusions to match?

**Comment by dopefishh** [comment]
We weren't aware of this, thanks for pointing it out. We will change it asap.
