### ISSUE TITLE
Use of deprecated font command

### ISSUE THREAD

**Issue by niluxv** [dopefishh/rutitlepage#14]
The seventeen layout uses the old deprecated `\sc` command for smallcaps in [this line](https://github.com/dopefishh/rutitlepage/blob/9b0c00f52f5b7741b0e311c42a4e00aec16d5ca5/rutitlepage.dtx#L194). This has long ago been deprecated, and KOMA script classes do not provide it anymore.

It should be replaced by `\scshape` or `\normalfont\scshape`.

**Comment by niluxv** [comment]
And similar for the `\it` in [this line](https://github.com/dopefishh/rutitlepage/blob/9b0c00f52f5b7741b0e311c42a4e00aec16d5ca5/rutitlepage.dtx#L193): `\itshape` or `\normalfont\itshape`.

**Comment by dopefishh** [comment]
Thanks!

**Comment by niluxv** [comment]
Thank you!
