### ISSUE TITLE
17/22: Support multi-line titles

### ISSUE THREAD

**Issue by niluxv** [dopefishh/rutitlepage#17]
I know it is not ideal, but sometimes a title needs to be rather long, and in particular with the seventeen and twentytwo layouts, a title can be so long that it requires more than a single line.

Currently the line does get broken as you would expect, but there is too little space between the two lines. In fact no leading is applied at all.

# Example/MWE

```latex
\documentclass{report}

\usepackage{rutitlepage}

\newcommand\theauthor{John Doe}
\newcommand\thedate{Tomorrow}
\newcommand\thecourse{Master’s Thesis}
\newcommand\thetitle{A Very Very Long Title May Break Lines if it is Long Enough}

\begin{document}
    \maketitleru[
        authors={\theauthor},
        date={\thedate},
        course={\thecourse},
        title={\thetitle},
    ]
\end{document}
```
[Output](https://github.com/user-attachments/files/16396011/main.pdf)

Note how the descenders in the top title line descend all the way to the ascenders in the bottom line.

# Fix

To apply the usual leading/linespread to a multiline title you could put the title in a vertical-mode box, e.g. a LaTeX `\parbox`  combined with `\raggedright`. Or maybe the `flushleft` environment works?

MWE:
```latex
\documentclass{report}

\usepackage{rutitlepage}

\newcommand\theauthor{John Doe}
\newcommand\thedate{Tomorrow}
\newcommand\thecourse{Master’s Thesis}
\newcommand\thetitle{A Very Very Long Title May Break Lines if it is Long Enough}

\begin{document}
    \newgeometry{left=25mm,top=25mm,right=15mm,bottom=10mm,hmarginratio=1:1}
    \begin{titlepage}%
        \null\vfill%
        \parindent0pt
        \textsc{\LARGE\thecourse}\\[1.5cm]
        %%% HERE %%%
        % This line below: note the \parbox to \textwidth and the \raggedright.
        \parbox{\textwidth}{\raggedright\Huge\bfseries\thetitle}%
        %%%
        \\[4\baselineskip]
        {\Large\scshape\theauthor}\\[\baselineskip]
        {\large\thedate}
        \vfill\vfill

        \hfill
        \includegraphics[width=80mm]{rutitlepage-logo-cmyk.pdf}\\
    \end{titlepage}
    \restoregeometry
\end{document}
```
[Output](https://github.com/user-attachments/files/16396026/fix.pdf)

As you can see, the normal linespread of 1.2 is now applied. (It also seems to affect linebreaking of the title.)

**Comment by dopefishh** [comment]
Thanks, this is a clear improvement. If you want you can make a PR, or I will fix it after my holidays.
